apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels:
    type: nfs001
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.200.141.154
    path: "/data/mysql"
    readOnly: false